name: AceMagic S1 Panel
version: "0.0.11"
slug: acemagic_s1
description: Add-on for controlling AceMagic S1 TFT/LCD and LED strip with integrated web GUI
url: "https://github.com/rlobanov/s1panel-ha-addon"
arch:
  - amd64
startup: application
boot: auto
init: false
ingress: true
ingress_port: 8686
panel_icon: mdi:monitor-dashboard
devices:
  - /dev/ttyUSB0:/dev/ttyUSB0:rwm
  - /dev/bus/usb:/dev/bus/usb:rwm
  - /dev/bus/usb/001/005
  - /dev/bus/usb/001/006
  - /dev/bus/usb/001/007
map:
  - config:rw
uart: true
usb: true
host_network: true
#apparmor: false  # Тест без этого, если возможно
privileged:
  - SYS_RAWIO
  - SYS_ADMIN
  - NET_ADMIN  # Для сетевого мониторинга
ports:
  8686/tcp: 8686
ports_description:
  8686/tcp: web interface
options:
  network_interface: "enp4s0"
  theme: "themes/simple_demo/portrait_simple.json"
  poll: 3000
  refresh: 1600
  heartbeat: 60000
schema:
  network_interface: str
  theme: str
  poll: int(500,10000)
  refresh: int(500,5000)
  heartbeat: int(10000,300000)








